id: P004204
initial_creation_type: ocr
created_at: 23/03/2020
last_modified_at: 2021-12-17 11:00:50.987749
source_metadata:
  id: bdr:W2PD17436
  title: གཉེན་སྒྲིག་བཅའ་ཁྲིམས་བསླབ་དེབ།
  author: ''
  volumes:
    e52c2347590e427ba159b80169eee406:
      image_group_id: I4PD3056
      title: ''
      volume_number: 1
      total_pages: 314
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
